# Generated by Django 3.2.13 on 2022-05-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_animals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='AnimalType',
        ),
    ]
