# Generated by Django 3.2.13 on 2022-05-12 18:07

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_animals', '0002_rename_type_animaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slogan', models.TextField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_animals_animals', to='home_animals.animaltype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
