# Generated by Django 3.2.13 on 2022-05-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_animals', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='basis',
            field=models.CharField(choices=[('A', 'Adoption'), ('F', 'Fostering')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('A', 'Aproved'), ('P', 'Pending'), ('R', 'Rejected')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
