# Generated by Django 3.2.13 on 2022-05-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_animals', '0005_auto_20220521_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
